### ISSUE TITLE
More info about Peers

### ISSUE THREAD

**Issue by efeefe** [subutai-io/bazaar#15] opened 2018-05-10 14:38 UTC
The participants of both workshops I gave here in Brazil asked whether the Bazaar plans to feature information about Peer connection quality as well as what it already shows on Peers page (uptime, RAM, disk...). It will be useful in order to select a Peer for one's envs and BPs.

**Comment by niclash** [comment] 2018-08-21 02:46
I think this is a duplicate of https://github.com/subutai-io/bazaar/issues/20, which now contains a long and full answer what the plan is.

**Closed as completed** 2018-08-21 12:49 UTC
